// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaCare.Infrastructure;

#nullable disable

namespace PharmaCare.Infrastructure.Migrations
{
    [DbContext(typeof(PharmaCareDBContext))]
    [Migration("20251216083045_AddStockTake")]
    partial class AddStockTake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Customers.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPurchases")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Customers.CustomerLedger", b =>
                {
                    b.Property<int>("LedgerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LedgerID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LedgerID");

                    b.HasIndex("CustomerID");

                    b.ToTable("CustomerLedgers");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Customers.LoyaltyTransaction", b =>
                {
                    b.Property<int>("LoyaltyTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoyaltyTransactionID"));

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PointsBalance")
                        .HasColumnType("int");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<int>("PointsRedeemed")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LoyaltyTransactionID");

                    b.HasIndex("CustomerID");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.Grn", b =>
                {
                    b.Property<int>("GrnID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrnID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrnNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PurchaseOrder_ID")
                        .HasColumnType("int");

                    b.Property<string>("ReceivedByRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("GrnID");

                    b.HasIndex("PurchaseOrder_ID");

                    b.ToTable("Grns");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.GrnItem", b =>
                {
                    b.Property<int>("GrnItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrnItemID"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Grn_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SupplierBatchRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrnItemID");

                    b.HasIndex("Grn_ID");

                    b.HasIndex("Product_ID");

                    b.ToTable("GrnItems");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Supplier_ID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PurchaseOrderID");

                    b.HasIndex("Supplier_ID");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.PurchaseOrderItem", b =>
                {
                    b.Property<int>("PurchaseOrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderItemID"));

                    b.Property<int?>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseOrder_ID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PurchaseOrderItemID");

                    b.HasIndex("Product_ID");

                    b.HasIndex("PurchaseOrder_ID");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockAdjustment", b =>
                {
                    b.Property<int>("StockAdjustmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockAdjustmentID"));

                    b.Property<int>("AdjustedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AdjustmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinancialImpact")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductBatch_ID")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAdjusted")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Store_ID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StockAdjustmentID");

                    b.HasIndex("ProductBatch_ID");

                    b.HasIndex("Store_ID");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockAlert", b =>
                {
                    b.Property<int>("StockAlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockAlertID"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Store_ID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StockAlertID");

                    b.HasIndex("Product_ID");

                    b.HasIndex("Store_ID");

                    b.ToTable("StockAlerts");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockMovement", b =>
                {
                    b.Property<int>("StockMovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockMovementID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductBatch_ID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Store_ID")
                        .HasColumnType("int");

                    b.HasKey("StockMovementID");

                    b.HasIndex("ProductBatch_ID");

                    b.HasIndex("Store_ID");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockTake", b =>
                {
                    b.Property<int>("StockTakeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTakeID"));

                    b.Property<int?>("CompletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Store_ID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StockTakeID");

                    b.HasIndex("Store_ID");

                    b.ToTable("StockTakes");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockTakeItem", b =>
                {
                    b.Property<int>("StockTakeItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTakeItemID"));

                    b.Property<int>("PhysicalQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductBatch_ID")
                        .HasColumnType("int");

                    b.Property<int>("StockTake_ID")
                        .HasColumnType("int");

                    b.Property<int>("SystemQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("VarianceCost")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("StockTakeItemID");

                    b.HasIndex("ProductBatch_ID");

                    b.HasIndex("StockTake_ID");

                    b.ToTable("StockTakeItems");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StoreInventory", b =>
                {
                    b.Property<int>("StoreInventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreInventoryID"));

                    b.Property<int?>("ProductBatch_ID")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int?>("Store_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StoreInventoryID");

                    b.HasIndex("ProductBatch_ID");

                    b.HasIndex("Store_ID");

                    b.ToTable("StoreInventories");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Membership.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserType_ID");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Membership.UserTypes", b =>
                {
                    b.Property<int>("UserTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTypeID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserTypeID");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            UserTypeID = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserType = "Admin"
                        },
                        new
                        {
                            UserTypeID = 2,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            UserType = "Pharmacist"
                        });
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Membership.UserWebPages", b =>
                {
                    b.Property<int>("UserWebPageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserWebPageID"));

                    b.Property<int>("SystemUser_ID")
                        .HasColumnType("int");

                    b.Property<int>("WebPage_ID")
                        .HasColumnType("int");

                    b.HasKey("UserWebPageID");

                    b.HasIndex("SystemUser_ID");

                    b.HasIndex("WebPage_ID");

                    b.ToTable("UserWebPages");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Membership.WebPageUrls", b =>
                {
                    b.Property<int>("WebPageUrlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebPageUrlID"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WebPage_ID")
                        .HasColumnType("int");

                    b.HasKey("WebPageUrlID");

                    b.HasIndex("WebPage_ID");

                    b.ToTable("WebPageUrls");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Membership.WebPages", b =>
                {
                    b.Property<int>("WebPageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebPageID"));

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("PageIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageOrder")
                        .HasColumnType("int");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Parent_ID")
                        .HasColumnType("int");

                    b.Property<string>("ViewName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WebPageID");

                    b.ToTable("WebPages");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Prescriptions.Prescription", b =>
                {
                    b.Property<int>("PrescriptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionID"));

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PrescriptionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrescriptionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionID");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Products.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategory_ID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("ParentCategory_ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Products.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Category_ID")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DosageForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxStockLevel")
                        .HasColumnType("int");

                    b.Property<int?>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("bit");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TherapeuticCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitOfMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductID");

                    b.HasIndex("Category_ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Products.ProductBatch", b =>
                {
                    b.Property<int>("ProductBatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductBatchID"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRecalled")
                        .HasColumnType("bit");

                    b.Property<decimal>("MRP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ManufacturingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Product_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecallDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecallReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupplierBatchRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductBatchID");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("Product_ID");

                    b.ToTable("ProductBatches");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.SaleManagement.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sale_ID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("Sale_ID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.SaleManagement.Sale", b =>
                {
                    b.Property<int>("SaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleID"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Prescription_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SaleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Store_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SaleID");

                    b.HasIndex("Customer_ID");

                    b.HasIndex("Prescription_ID");

                    b.HasIndex("Store_ID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.SaleManagement.SaleLine", b =>
                {
                    b.Property<int>("SaleLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleLineID"));

                    b.Property<int?>("ProductBatch_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Sale_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleLineID");

                    b.HasIndex("ProductBatch_ID");

                    b.HasIndex("Product_ID");

                    b.HasIndex("Sale_ID");

                    b.ToTable("SaleLines");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Stores.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoreID");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreID = 1,
                            Code = "MAIN-001",
                            Name = "PharmaCare Main Store"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Membership.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Membership.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Models.Membership.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Membership.SystemUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Customers.CustomerLedger", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Customers.Customer", "Customer")
                        .WithMany("Ledgers")
                        .HasForeignKey("CustomerID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Customers.LoyaltyTransaction", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Customers.Customer", "Customer")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("CustomerID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.Grn", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Inventory.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrder_ID");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.GrnItem", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Inventory.Grn", "Grn")
                        .WithMany("GrnItems")
                        .HasForeignKey("Grn_ID");

                    b.HasOne("PharmaCare.Domain.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID");

                    b.Navigation("Grn");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.PurchaseOrder", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Inventory.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("Supplier_ID")
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.PurchaseOrderItem", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID");

                    b.HasOne("PharmaCare.Domain.Models.Inventory.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("PurchaseOrder_ID");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockAdjustment", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Products.ProductBatch", "ProductBatch")
                        .WithMany()
                        .HasForeignKey("ProductBatch_ID")
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID")
                        .IsRequired();

                    b.Navigation("ProductBatch");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockAlert", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID");

                    b.HasOne("PharmaCare.Domain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID");

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockMovement", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Products.ProductBatch", "ProductBatch")
                        .WithMany()
                        .HasForeignKey("ProductBatch_ID");

                    b.HasOne("PharmaCare.Domain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID");

                    b.Navigation("ProductBatch");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockTake", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID")
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockTakeItem", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Products.ProductBatch", "ProductBatch")
                        .WithMany()
                        .HasForeignKey("ProductBatch_ID")
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Models.Inventory.StockTake", "StockTake")
                        .WithMany("StockTakeItems")
                        .HasForeignKey("StockTake_ID")
                        .IsRequired();

                    b.Navigation("ProductBatch");

                    b.Navigation("StockTake");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StoreInventory", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Products.ProductBatch", "ProductBatch")
                        .WithMany("StoreInventories")
                        .HasForeignKey("ProductBatch_ID");

                    b.HasOne("PharmaCare.Domain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID");

                    b.Navigation("ProductBatch");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Membership.SystemUser", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Membership.UserTypes", "UserType")
                        .WithMany()
                        .HasForeignKey("UserType_ID")
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Membership.UserWebPages", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Membership.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUser_ID")
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Models.Membership.WebPages", "WebPage")
                        .WithMany()
                        .HasForeignKey("WebPage_ID")
                        .IsRequired();

                    b.Navigation("SystemUser");

                    b.Navigation("WebPage");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Membership.WebPageUrls", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Membership.WebPages", "WebPage")
                        .WithMany("WebPageUrls")
                        .HasForeignKey("WebPage_ID")
                        .IsRequired();

                    b.Navigation("WebPage");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Products.Category", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Products.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategory_ID");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Products.Product", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Products.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Category_ID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Products.ProductBatch", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Products.Product", "Product")
                        .WithMany("ProductBatches")
                        .HasForeignKey("Product_ID");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.SaleManagement.Payment", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.SaleManagement.Sale", "Sale")
                        .WithMany("Payments")
                        .HasForeignKey("Sale_ID");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.SaleManagement.Sale", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Customer_ID");

                    b.HasOne("PharmaCare.Domain.Models.Prescriptions.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("Prescription_ID");

                    b.HasOne("PharmaCare.Domain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID");

                    b.Navigation("Customer");

                    b.Navigation("Prescription");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.SaleManagement.SaleLine", b =>
                {
                    b.HasOne("PharmaCare.Domain.Models.Products.ProductBatch", "ProductBatch")
                        .WithMany()
                        .HasForeignKey("ProductBatch_ID");

                    b.HasOne("PharmaCare.Domain.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID");

                    b.HasOne("PharmaCare.Domain.Models.SaleManagement.Sale", "Sale")
                        .WithMany("SaleLines")
                        .HasForeignKey("Sale_ID");

                    b.Navigation("Product");

                    b.Navigation("ProductBatch");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Customers.Customer", b =>
                {
                    b.Navigation("Ledgers");

                    b.Navigation("LoyaltyTransactions");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.Grn", b =>
                {
                    b.Navigation("GrnItems");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderItems");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Inventory.StockTake", b =>
                {
                    b.Navigation("StockTakeItems");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Membership.WebPages", b =>
                {
                    b.Navigation("WebPageUrls");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Products.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Products.Product", b =>
                {
                    b.Navigation("ProductBatches");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.Products.ProductBatch", b =>
                {
                    b.Navigation("StoreInventories");
                });

            modelBuilder.Entity("PharmaCare.Domain.Models.SaleManagement.Sale", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("SaleLines");
                });
#pragma warning restore 612, 618
        }
    }
}
