// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmaCare.Infrastructure;

#nullable disable

namespace PharmaCare.Infrastructure.Migrations
{
    [DbContext(typeof(PharmaCareDBContext))]
    [Migration("20260130162326_ModifyPartyAndProductEntities")]
    partial class ModifyPartyAndProductEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("IdentityRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("IdentityRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IdentityUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("IdentityUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("IdentityUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("IdentityUserTokens", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<int?>("AccountHead_ID")
                        .HasColumnType("int");

                    b.Property<int>("AccountSubhead_ID")
                        .HasColumnType("int");

                    b.Property<int>("AccountType_ID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemAccount")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("AccountID");

                    b.HasIndex("AccountHead_ID");

                    b.HasIndex("AccountSubhead_ID");

                    b.HasIndex("AccountType_ID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.AccountFamily", b =>
                {
                    b.Property<int>("AccountFamilyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountFamilyID"));

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountFamilyID");

                    b.ToTable("AccountFamilies", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.AccountHead", b =>
                {
                    b.Property<int>("AccountHeadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountHeadID"));

                    b.Property<int>("AccountFamily_ID")
                        .HasColumnType("int");

                    b.Property<string>("HeadName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountHeadID");

                    b.HasIndex("AccountFamily_ID");

                    b.ToTable("AccountHeads", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.AccountSubhead", b =>
                {
                    b.Property<int>("AccountSubheadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountSubheadID"));

                    b.Property<int>("AccountHead_ID")
                        .HasColumnType("int");

                    b.Property<string>("SubheadName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountSubheadID");

                    b.HasIndex("AccountHead_ID");

                    b.ToTable("AccountSubheads", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.AccountType", b =>
                {
                    b.Property<int>("AccountTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountTypeID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountTypeID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AccountTypes", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<int?>("COGSAccount_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DamageAccount_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SaleAccount_ID")
                        .HasColumnType("int");

                    b.Property<int?>("StockAccount_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("COGSAccount_ID");

                    b.HasIndex("DamageAccount_ID");

                    b.HasIndex("SaleAccount_ID");

                    b.HasIndex("StockAccount_ID");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.Party", b =>
                {
                    b.Property<int>("PartyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartyID"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IBAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PartyID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.PriceType", b =>
                {
                    b.Property<int>("PriceTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceTypeID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PriceTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PriceTypeID");

                    b.ToTable("PriceTypes", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("Category_ID")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubCategory_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("Category_ID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ShortCode");

                    b.HasIndex("SubCategory_ID");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.ProductPrice", b =>
                {
                    b.Property<int>("ProductPriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductPriceID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PriceType_ID")
                        .HasColumnType("int");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProductPriceID");

                    b.HasIndex("PriceType_ID");

                    b.HasIndex("Product_ID");

                    b.ToTable("ProductPrices", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("StoreID");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryID"));

                    b.Property<int>("Category_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("SubCategoryID");

                    b.HasIndex("Category_ID");

                    b.ToTable("SubCategories", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Finance.Expense", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExpenseAccount_ID")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseCategory_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SourceAccount_ID")
                        .HasColumnType("int");

                    b.Property<int>("Store_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Voucher_ID")
                        .HasColumnType("int");

                    b.HasKey("ExpenseID");

                    b.HasIndex("ExpenseAccount_ID");

                    b.HasIndex("ExpenseCategory_ID");

                    b.HasIndex("SourceAccount_ID");

                    b.HasIndex("Store_ID");

                    b.HasIndex("Voucher_ID");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Finance.ExpenseCategory", b =>
                {
                    b.Property<int>("ExpenseCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseCategoryID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultExpenseAccount_ID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Parent_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ExpenseCategoryID");

                    b.HasIndex("DefaultExpenseAccount_ID");

                    b.HasIndex("Parent_ID");

                    b.ToTable("ExpenseCategories", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Finance.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<int>("Account_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ChequeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChequeNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Party_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("StockMain_ID")
                        .HasColumnType("int");

                    b.Property<int>("Store_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("Voucher_ID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("Account_ID");

                    b.HasIndex("Party_ID");

                    b.HasIndex("StockMain_ID");

                    b.HasIndex("Store_ID");

                    b.HasIndex("Voucher_ID");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Inventory.StoreInventory", b =>
                {
                    b.Property<int>("StoreInventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreInventoryID"));

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Store_ID")
                        .HasColumnType("int");

                    b.HasKey("StoreInventoryID");

                    b.HasIndex("Product_ID");

                    b.HasIndex("Store_ID", "Product_ID")
                        .IsUnique();

                    b.ToTable("StoreInventories", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.Page", b =>
                {
                    b.Property<int>("PageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageID"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Controller")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int?>("Parent_ID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PageID");

                    b.HasIndex("Parent_ID");

                    b.ToTable("Pages", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.PageUrl", b =>
                {
                    b.Property<int>("PageUrlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageUrlID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Page_ID")
                        .HasColumnType("int");

                    b.HasKey("PageUrlID");

                    b.HasIndex("Page_ID");

                    b.HasIndex("Controller", "Action");

                    b.ToTable("PageUrls", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("RoleID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.RolePage", b =>
                {
                    b.Property<int>("RolePageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePageID"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<int>("Page_ID")
                        .HasColumnType("int");

                    b.Property<int>("Role_ID")
                        .HasColumnType("int");

                    b.HasKey("RolePageID");

                    b.HasIndex("Page_ID");

                    b.HasIndex("Role_ID", "Page_ID")
                        .IsUnique();

                    b.ToTable("RolePages", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Store_ID")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("Store_ID");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.UserRole", b =>
                {
                    b.Property<int>("UserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleID"));

                    b.Property<int>("Role_ID")
                        .HasColumnType("int");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("UserRoleID");

                    b.HasIndex("Role_ID");

                    b.HasIndex("User_ID", "Role_ID")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.StockDetail", b =>
                {
                    b.Property<int>("StockDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockDetailID"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("LineCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Product_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StockMain_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StockDetailID");

                    b.HasIndex("Product_ID");

                    b.HasIndex("StockMain_ID");

                    b.ToTable("StockDetails", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.StockMain", b =>
                {
                    b.Property<int>("StockMainID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockMainID"));

                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationStore_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Party_ID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReceivedBy")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceStockMain_ID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Store_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TransactionType_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VoidedBy")
                        .HasColumnType("int");

                    b.Property<int?>("Voucher_ID")
                        .HasColumnType("int");

                    b.HasKey("StockMainID");

                    b.HasIndex("DestinationStore_ID");

                    b.HasIndex("Party_ID");

                    b.HasIndex("ReferenceStockMain_ID");

                    b.HasIndex("Store_ID");

                    b.HasIndex("TransactionNo")
                        .IsUnique();

                    b.HasIndex("TransactionType_ID");

                    b.HasIndex("Voucher_ID");

                    b.ToTable("StockMains", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.TransactionType", b =>
                {
                    b.Property<int>("TransactionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionTypeID"));

                    b.Property<bool>("AffectsStock")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("CreatesVoucher")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockDirection")
                        .HasColumnType("int");

                    b.HasKey("TransactionTypeID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TransactionTypes", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.Voucher", b =>
                {
                    b.Property<int>("VoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsReversed")
                        .HasColumnType("bit");

                    b.Property<string>("Narration")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReversedByVoucher_ID")
                        .HasColumnType("int");

                    b.Property<int?>("ReversesVoucher_ID")
                        .HasColumnType("int");

                    b.Property<int?>("SourceID")
                        .HasColumnType("int");

                    b.Property<string>("SourceTable")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Store_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("VoucherDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VoucherType_ID")
                        .HasColumnType("int");

                    b.HasKey("VoucherID");

                    b.HasIndex("ReversedByVoucher_ID")
                        .IsUnique()
                        .HasFilter("[ReversedByVoucher_ID] IS NOT NULL");

                    b.HasIndex("ReversesVoucher_ID")
                        .IsUnique()
                        .HasFilter("[ReversesVoucher_ID] IS NOT NULL");

                    b.HasIndex("Store_ID");

                    b.HasIndex("VoucherNo")
                        .IsUnique();

                    b.HasIndex("VoucherType_ID");

                    b.ToTable("Vouchers", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.VoucherDetail", b =>
                {
                    b.Property<int>("VoucherDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherDetailID"));

                    b.Property<int>("Account_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Party_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Product_ID")
                        .HasColumnType("int");

                    b.Property<int>("Voucher_ID")
                        .HasColumnType("int");

                    b.HasKey("VoucherDetailID");

                    b.HasIndex("Account_ID");

                    b.HasIndex("Party_ID");

                    b.HasIndex("Product_ID");

                    b.HasIndex("Voucher_ID");

                    b.ToTable("VoucherDetails", (string)null);
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.VoucherType", b =>
                {
                    b.Property<int>("VoucherTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherTypeID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VoucherTypeID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("VoucherTypes", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Security.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Security.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Security.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Security.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.Account", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Accounting.AccountHead", "AccountHead")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountHead_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaCare.Domain.Entities.Accounting.AccountSubhead", "AccountSubhead")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountSubhead_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Accounting.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountType_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountHead");

                    b.Navigation("AccountSubhead");

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.AccountHead", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Accounting.AccountFamily", "AccountFamily")
                        .WithMany("AccountHeads")
                        .HasForeignKey("AccountFamily_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountFamily");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.AccountSubhead", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Accounting.AccountHead", "AccountHead")
                        .WithMany("AccountSubheads")
                        .HasForeignKey("AccountHead_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountHead");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.Category", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Accounting.Account", "COGSAccount")
                        .WithMany()
                        .HasForeignKey("COGSAccount_ID");

                    b.HasOne("PharmaCare.Domain.Entities.Accounting.Account", "DamageAccount")
                        .WithMany()
                        .HasForeignKey("DamageAccount_ID");

                    b.HasOne("PharmaCare.Domain.Entities.Accounting.Account", "SaleAccount")
                        .WithMany()
                        .HasForeignKey("SaleAccount_ID");

                    b.HasOne("PharmaCare.Domain.Entities.Accounting.Account", "StockAccount")
                        .WithMany()
                        .HasForeignKey("StockAccount_ID");

                    b.Navigation("COGSAccount");

                    b.Navigation("DamageAccount");

                    b.Navigation("SaleAccount");

                    b.Navigation("StockAccount");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.Product", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("Category_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategory_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.ProductPrice", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Configuration.PriceType", "PriceType")
                        .WithMany()
                        .HasForeignKey("PriceType_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.SubCategory", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("Category_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Finance.Expense", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Accounting.Account", "ExpenseAccount")
                        .WithMany()
                        .HasForeignKey("ExpenseAccount_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Finance.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseCategory_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Accounting.Account", "SourceAccount")
                        .WithMany()
                        .HasForeignKey("SourceAccount_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Transactions.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("Voucher_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ExpenseAccount");

                    b.Navigation("ExpenseCategory");

                    b.Navigation("SourceAccount");

                    b.Navigation("Store");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Finance.ExpenseCategory", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Accounting.Account", "DefaultExpenseAccount")
                        .WithMany()
                        .HasForeignKey("DefaultExpenseAccount_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PharmaCare.Domain.Entities.Finance.ExpenseCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("Parent_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultExpenseAccount");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Finance.Payment", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Accounting.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Party", "Party")
                        .WithMany()
                        .HasForeignKey("Party_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Transactions.StockMain", "StockMain")
                        .WithMany()
                        .HasForeignKey("StockMain_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Transactions.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("Voucher_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Party");

                    b.Navigation("StockMain");

                    b.Navigation("Store");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Inventory.StoreInventory", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.Page", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Security.Page", "ParentPage")
                        .WithMany("ChildPages")
                        .HasForeignKey("Parent_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPage");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.PageUrl", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Security.Page", "Page")
                        .WithMany("PageUrls")
                        .HasForeignKey("Page_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.RolePage", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Security.Page", "Page")
                        .WithMany("RolePages")
                        .HasForeignKey("Page_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Security.Role", "Role")
                        .WithMany("RolePages")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.User", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.UserRole", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Security.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Security.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.StockDetail", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Transactions.StockMain", "StockMain")
                        .WithMany("StockDetails")
                        .HasForeignKey("StockMain_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockMain");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.StockMain", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Store", "DestinationStore")
                        .WithMany()
                        .HasForeignKey("DestinationStore_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Party", "Party")
                        .WithMany()
                        .HasForeignKey("Party_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PharmaCare.Domain.Entities.Transactions.StockMain", "ReferenceStockMain")
                        .WithMany()
                        .HasForeignKey("ReferenceStockMain_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Transactions.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionType_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Transactions.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("Voucher_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DestinationStore");

                    b.Navigation("Party");

                    b.Navigation("ReferenceStockMain");

                    b.Navigation("Store");

                    b.Navigation("TransactionType");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.Voucher", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Transactions.Voucher", "ReversedByVoucher")
                        .WithOne()
                        .HasForeignKey("PharmaCare.Domain.Entities.Transactions.Voucher", "ReversedByVoucher_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaCare.Domain.Entities.Transactions.Voucher", "ReversesVoucher")
                        .WithOne()
                        .HasForeignKey("PharmaCare.Domain.Entities.Transactions.Voucher", "ReversesVoucher_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Store", "Store")
                        .WithMany()
                        .HasForeignKey("Store_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PharmaCare.Domain.Entities.Transactions.VoucherType", "VoucherType")
                        .WithMany()
                        .HasForeignKey("VoucherType_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReversedByVoucher");

                    b.Navigation("ReversesVoucher");

                    b.Navigation("Store");

                    b.Navigation("VoucherType");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.VoucherDetail", b =>
                {
                    b.HasOne("PharmaCare.Domain.Entities.Accounting.Account", "Account")
                        .WithMany()
                        .HasForeignKey("Account_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Party", "Party")
                        .WithMany()
                        .HasForeignKey("Party_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PharmaCare.Domain.Entities.Configuration.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PharmaCare.Domain.Entities.Transactions.Voucher", "Voucher")
                        .WithMany("VoucherDetails")
                        .HasForeignKey("Voucher_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Party");

                    b.Navigation("Product");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.AccountFamily", b =>
                {
                    b.Navigation("AccountHeads");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.AccountHead", b =>
                {
                    b.Navigation("AccountSubheads");

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.AccountSubhead", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Accounting.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Configuration.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Finance.ExpenseCategory", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.Page", b =>
                {
                    b.Navigation("ChildPages");

                    b.Navigation("PageUrls");

                    b.Navigation("RolePages");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.Role", b =>
                {
                    b.Navigation("RolePages");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Security.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.StockMain", b =>
                {
                    b.Navigation("StockDetails");
                });

            modelBuilder.Entity("PharmaCare.Domain.Entities.Transactions.Voucher", b =>
                {
                    b.Navigation("VoucherDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
