using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace PharmaCare.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class DatabaseHardening_Step51 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_StockMovements_ProductBatches_ProductBatch_ID",
                table: "StockMovements");

            // NOTE: Commented out seed data deletions - data already exists in database
            // These were auto-generated by EF and cause FK constraint violations
            // migrationBuilder.DeleteData(table: "AccountTypes", keyColumn: "AccountTypeID", keyValue: 1);
            // migrationBuilder.DeleteData(table: "AccountTypes", keyColumn: "AccountTypeID", keyValue: 2);
            // migrationBuilder.DeleteData(table: "AccountTypes", keyColumn: "AccountTypeID", keyValue: 3);
            // migrationBuilder.DeleteData(table: "AccountTypes", keyColumn: "AccountTypeID", keyValue: 4);
            // migrationBuilder.DeleteData(table: "AccountTypes", keyColumn: "AccountTypeID", keyValue: 5);
            // migrationBuilder.DeleteData(table: "AccountTypes", keyColumn: "AccountTypeID", keyValue: 6);
            // migrationBuilder.DeleteData(table: "AccountTypes", keyColumn: "AccountTypeID", keyValue: 7);
            // migrationBuilder.DeleteData(table: "AccountTypes", keyColumn: "AccountTypeID", keyValue: 8);
            // migrationBuilder.DeleteData(table: "AccountTypes", keyColumn: "AccountTypeID", keyValue: 9);
            // migrationBuilder.DeleteData(table: "Stores", keyColumn: "StoreID", keyValue: 1);
            // migrationBuilder.DeleteData(table: "UserTypes", keyColumn: "UserTypeID", keyValue: 1);
            // migrationBuilder.DeleteData(table: "UserTypes", keyColumn: "UserTypeID", keyValue: 2);

            migrationBuilder.AlterColumn<int>(
                name: "ReferenceID",
                table: "StockMovements",
                type: "int",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AlterColumn<decimal>(
                name: "Quantity",
                table: "StockMovements",
                type: "decimal(18,4)",
                nullable: false,
                oldClrType: typeof(decimal),
                oldType: "decimal(18,2)");

            migrationBuilder.AlterColumn<int>(
                name: "ProductBatch_ID",
                table: "StockMovements",
                type: "int",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AddColumn<int>(
                name: "JournalEntry_ID",
                table: "StockMovements",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ReferenceNumber",
                table: "StockMovements",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "ReferenceType",
                table: "StockMovements",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "RelatedMovement_ID",
                table: "StockMovements",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<decimal>(
                name: "TotalCost",
                table: "StockMovements",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "UnitCost",
                table: "StockMovements",
                type: "decimal(18,4)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<int>(
                name: "FiscalPeriod_ID",
                table: "JournalEntries",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsSystemEntry",
                table: "JournalEntries",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<int>(
                name: "Store_ID",
                table: "JournalEntries",
                type: "int",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "FiscalYears",
                columns: table => new
                {
                    FiscalYearID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    YearCode = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    YearName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    StartDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    EndDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Status = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    ClosedBy = table.Column<int>(type: "int", nullable: true),
                    ClosedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<int>(type: "int", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedBy = table.Column<int>(type: "int", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FiscalYears", x => x.FiscalYearID);
                });

            migrationBuilder.CreateTable(
                name: "JournalEntrySequences",
                columns: table => new
                {
                    Year = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    NextNumber = table.Column<int>(type: "int", nullable: false),
                    RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_JournalEntrySequences", x => x.Year);
                });

            migrationBuilder.CreateTable(
                name: "FiscalPeriods",
                columns: table => new
                {
                    FiscalPeriodID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FiscalYear_ID = table.Column<int>(type: "int", nullable: false),
                    PeriodNumber = table.Column<int>(type: "int", nullable: false),
                    PeriodCode = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    PeriodName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    StartDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    EndDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Status = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    ClosedBy = table.Column<int>(type: "int", nullable: true),
                    ClosedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    LockedBy = table.Column<int>(type: "int", nullable: true),
                    LockedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<int>(type: "int", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedBy = table.Column<int>(type: "int", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FiscalPeriods", x => x.FiscalPeriodID);
                    table.ForeignKey(
                        name: "FK_FiscalPeriods_FiscalYears_FiscalYear_ID",
                        column: x => x.FiscalYear_ID,
                        principalTable: "FiscalYears",
                        principalColumn: "FiscalYearID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "PeriodOverrides",
                columns: table => new
                {
                    PeriodOverrideID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FiscalPeriod_ID = table.Column<int>(type: "int", nullable: false),
                    Store_ID = table.Column<int>(type: "int", nullable: true),
                    JournalEntry_ID = table.Column<int>(type: "int", nullable: false),
                    Reason = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ApprovedBy = table.Column<int>(type: "int", nullable: false),
                    ApprovedDate = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PeriodOverrides", x => x.PeriodOverrideID);
                    table.ForeignKey(
                        name: "FK_PeriodOverrides_FiscalPeriods_FiscalPeriod_ID",
                        column: x => x.FiscalPeriod_ID,
                        principalTable: "FiscalPeriods",
                        principalColumn: "FiscalPeriodID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_PeriodOverrides_JournalEntries_JournalEntry_ID",
                        column: x => x.JournalEntry_ID,
                        principalTable: "JournalEntries",
                        principalColumn: "JournalEntryID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "StoreFiscalPeriods",
                columns: table => new
                {
                    StoreFiscalPeriodID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Store_ID = table.Column<int>(type: "int", nullable: false),
                    FiscalPeriod_ID = table.Column<int>(type: "int", nullable: false),
                    Status = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    ClosedBy = table.Column<int>(type: "int", nullable: true),
                    ClosedDate = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StoreFiscalPeriods", x => x.StoreFiscalPeriodID);
                    table.ForeignKey(
                        name: "FK_StoreFiscalPeriods_FiscalPeriods_FiscalPeriod_ID",
                        column: x => x.FiscalPeriod_ID,
                        principalTable: "FiscalPeriods",
                        principalColumn: "FiscalPeriodID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_StoreFiscalPeriods_Stores_Store_ID",
                        column: x => x.Store_ID,
                        principalTable: "Stores",
                        principalColumn: "StoreID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_StockMovements_JournalEntry_ID",
                table: "StockMovements",
                column: "JournalEntry_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockMovements_RelatedMovement_ID",
                table: "StockMovements",
                column: "RelatedMovement_ID",
                unique: true,
                filter: "[RelatedMovement_ID] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_JournalEntries_FiscalPeriod_ID",
                table: "JournalEntries",
                column: "FiscalPeriod_ID");

            migrationBuilder.CreateIndex(
                name: "IX_FiscalPeriods_FiscalYear_ID",
                table: "FiscalPeriods",
                column: "FiscalYear_ID");

            migrationBuilder.CreateIndex(
                name: "IX_FiscalPeriods_PeriodCode",
                table: "FiscalPeriods",
                column: "PeriodCode",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_FiscalPeriods_StartDate_EndDate",
                table: "FiscalPeriods",
                columns: new[] { "StartDate", "EndDate" });

            migrationBuilder.CreateIndex(
                name: "IX_FiscalYears_YearCode",
                table: "FiscalYears",
                column: "YearCode",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_PeriodOverrides_FiscalPeriod_ID",
                table: "PeriodOverrides",
                column: "FiscalPeriod_ID");

            migrationBuilder.CreateIndex(
                name: "IX_PeriodOverrides_JournalEntry_ID",
                table: "PeriodOverrides",
                column: "JournalEntry_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StoreFiscalPeriods_FiscalPeriod_ID",
                table: "StoreFiscalPeriods",
                column: "FiscalPeriod_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StoreFiscalPeriods_Store_ID_FiscalPeriod_ID",
                table: "StoreFiscalPeriods",
                columns: new[] { "Store_ID", "FiscalPeriod_ID" },
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_JournalEntries_FiscalPeriods_FiscalPeriod_ID",
                table: "JournalEntries",
                column: "FiscalPeriod_ID",
                principalTable: "FiscalPeriods",
                principalColumn: "FiscalPeriodID",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "FK_StockMovements_JournalEntries_JournalEntry_ID",
                table: "StockMovements",
                column: "JournalEntry_ID",
                principalTable: "JournalEntries",
                principalColumn: "JournalEntryID",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "FK_StockMovements_ProductBatches_ProductBatch_ID",
                table: "StockMovements",
                column: "ProductBatch_ID",
                principalTable: "ProductBatches",
                principalColumn: "ProductBatchID",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_StockMovements_StockMovements_RelatedMovement_ID",
                table: "StockMovements",
                column: "RelatedMovement_ID",
                principalTable: "StockMovements",
                principalColumn: "StockMovementID");

            // ========== STEP 5.1 DATABASE HARDENING CONSTRAINTS ==========

            // CHECK: Enforce Debit = Credit at database level
            migrationBuilder.Sql(@"
                ALTER TABLE JournalEntries
                ADD CONSTRAINT CHK_JournalEntry_DebitEqualsCredit
                CHECK (TotalDebit = TotalCredit);
            ");

            // CHECK: Prevent negative amounts on journal lines
            migrationBuilder.Sql(@"
                ALTER TABLE JournalEntryLines
                ADD CONSTRAINT CHK_JournalEntryLine_NonNegativeDebit
                CHECK (DebitAmount >= 0);

                ALTER TABLE JournalEntryLines
                ADD CONSTRAINT CHK_JournalEntryLine_NonNegativeCredit
                CHECK (CreditAmount >= 0);
            ");

            // CHECK: Each line must have EITHER debit OR credit (not both, not neither)
            migrationBuilder.Sql(@"
                ALTER TABLE JournalEntryLines
                ADD CONSTRAINT CHK_JournalEntryLine_ExclusiveDebitCredit
                CHECK (
                    (DebitAmount > 0 AND CreditAmount = 0) OR
                    (DebitAmount = 0 AND CreditAmount > 0)
                );
            ");

            // CHECK: FiscalYear/FiscalPeriod status must be valid
            migrationBuilder.Sql(@"
                ALTER TABLE FiscalYears
                ADD CONSTRAINT CHK_FiscalYear_ValidStatus
                CHECK (Status IN ('Open', 'Closed', 'Locked'));

                ALTER TABLE FiscalPeriods
                ADD CONSTRAINT CHK_FiscalPeriod_ValidStatus
                CHECK (Status IN ('Open', 'Closed', 'Locked'));

                ALTER TABLE StoreFiscalPeriods
                ADD CONSTRAINT CHK_StoreFiscalPeriod_ValidStatus
                CHECK (Status IN ('Open', 'Closed', 'Locked'));
            ");

            // TRIGGER: Prevent modification of Posted journal entries (except status change to Void)
            migrationBuilder.Sql(@"
                CREATE TRIGGER TR_JournalEntries_PreventPostedModification
                ON JournalEntries
                AFTER UPDATE
                AS
                BEGIN
                    SET NOCOUNT ON;
                    
                    -- Check if any posted entries are being modified (not just voided)
                    IF EXISTS (
                        SELECT 1 
                        FROM deleted d
                        INNER JOIN inserted i ON d.JournalEntryID = i.JournalEntryID
                        WHERE d.Status = 'Posted'
                          AND NOT (i.Status = 'Void' AND d.Status = 'Posted')  -- Allow only Posted->Void
                          AND (
                              d.TotalDebit != i.TotalDebit OR
                              d.TotalCredit != i.TotalCredit OR
                              d.Description != i.Description OR
                              d.EntryDate != i.EntryDate OR
                              d.PostingDate != i.PostingDate OR
                              d.EntryType != i.EntryType
                          )
                    )
                    BEGIN
                        RAISERROR('Posted journal entries cannot be modified. Create a reversing entry to void.', 16, 1);
                        ROLLBACK TRANSACTION;
                        RETURN;
                    END
                END;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // ========== Drop STEP 5.1 CONSTRAINTS & TRIGGERS ==========
            migrationBuilder.Sql("DROP TRIGGER IF EXISTS TR_JournalEntries_PreventPostedModification;");
            migrationBuilder.Sql("ALTER TABLE StoreFiscalPeriods DROP CONSTRAINT IF EXISTS CHK_StoreFiscalPeriod_ValidStatus;");
            migrationBuilder.Sql("ALTER TABLE FiscalPeriods DROP CONSTRAINT IF EXISTS CHK_FiscalPeriod_ValidStatus;");
            migrationBuilder.Sql("ALTER TABLE FiscalYears DROP CONSTRAINT IF EXISTS CHK_FiscalYear_ValidStatus;");
            migrationBuilder.Sql("ALTER TABLE JournalEntryLines DROP CONSTRAINT IF EXISTS CHK_JournalEntryLine_ExclusiveDebitCredit;");
            migrationBuilder.Sql("ALTER TABLE JournalEntryLines DROP CONSTRAINT IF EXISTS CHK_JournalEntryLine_NonNegativeCredit;");
            migrationBuilder.Sql("ALTER TABLE JournalEntryLines DROP CONSTRAINT IF EXISTS CHK_JournalEntryLine_NonNegativeDebit;");
            migrationBuilder.Sql("ALTER TABLE JournalEntries DROP CONSTRAINT IF EXISTS CHK_JournalEntry_DebitEqualsCredit;");

            migrationBuilder.DropForeignKey(
                name: "FK_JournalEntries_FiscalPeriods_FiscalPeriod_ID",
                table: "JournalEntries");

            migrationBuilder.DropForeignKey(
                name: "FK_StockMovements_JournalEntries_JournalEntry_ID",
                table: "StockMovements");

            migrationBuilder.DropForeignKey(
                name: "FK_StockMovements_ProductBatches_ProductBatch_ID",
                table: "StockMovements");

            migrationBuilder.DropForeignKey(
                name: "FK_StockMovements_StockMovements_RelatedMovement_ID",
                table: "StockMovements");

            migrationBuilder.DropTable(
                name: "JournalEntrySequences");

            migrationBuilder.DropTable(
                name: "PeriodOverrides");

            migrationBuilder.DropTable(
                name: "StoreFiscalPeriods");

            migrationBuilder.DropTable(
                name: "FiscalPeriods");

            migrationBuilder.DropTable(
                name: "FiscalYears");

            migrationBuilder.DropIndex(
                name: "IX_StockMovements_JournalEntry_ID",
                table: "StockMovements");

            migrationBuilder.DropIndex(
                name: "IX_StockMovements_RelatedMovement_ID",
                table: "StockMovements");

            migrationBuilder.DropIndex(
                name: "IX_JournalEntries_FiscalPeriod_ID",
                table: "JournalEntries");

            migrationBuilder.DropColumn(
                name: "JournalEntry_ID",
                table: "StockMovements");

            migrationBuilder.DropColumn(
                name: "ReferenceNumber",
                table: "StockMovements");

            migrationBuilder.DropColumn(
                name: "ReferenceType",
                table: "StockMovements");

            migrationBuilder.DropColumn(
                name: "RelatedMovement_ID",
                table: "StockMovements");

            migrationBuilder.DropColumn(
                name: "TotalCost",
                table: "StockMovements");

            migrationBuilder.DropColumn(
                name: "UnitCost",
                table: "StockMovements");

            migrationBuilder.DropColumn(
                name: "FiscalPeriod_ID",
                table: "JournalEntries");

            migrationBuilder.DropColumn(
                name: "IsSystemEntry",
                table: "JournalEntries");

            migrationBuilder.DropColumn(
                name: "Store_ID",
                table: "JournalEntries");

            migrationBuilder.AlterColumn<string>(
                name: "ReferenceID",
                table: "StockMovements",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(int),
                oldType: "int",
                oldNullable: true);

            migrationBuilder.AlterColumn<decimal>(
                name: "Quantity",
                table: "StockMovements",
                type: "decimal(18,2)",
                nullable: false,
                oldClrType: typeof(decimal),
                oldType: "decimal(18,4)");

            migrationBuilder.AlterColumn<int>(
                name: "ProductBatch_ID",
                table: "StockMovements",
                type: "int",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "int");

            // NOTE: Commented out seed data insertions - data already exists in database
            // These were auto-generated by EF to match the deletions in Up()
            // migrationBuilder.InsertData(table: "AccountTypes", ...);
            // migrationBuilder.InsertData(table: "Stores", ...);
            // migrationBuilder.InsertData(table: "UserTypes", ...);

            migrationBuilder.AddForeignKey(
                name: "FK_StockMovements_ProductBatches_ProductBatch_ID",
                table: "StockMovements",
                column: "ProductBatch_ID",
                principalTable: "ProductBatches",
                principalColumn: "ProductBatchID",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
