using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PharmaCare.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddUnifiedTransactionTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AccountVoucherTypes",
                columns: table => new
                {
                    VoucherTypeID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Code = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false),
                    Name = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    AutoGenerated = table.Column<bool>(type: "bit", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AccountVoucherTypes", x => x.VoucherTypeID);
                });

            migrationBuilder.CreateTable(
                name: "InvoiceTypes",
                columns: table => new
                {
                    TypeID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Code = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    Name = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Category = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    Direction = table.Column<int>(type: "int", nullable: false),
                    AffectsStock = table.Column<bool>(type: "bit", nullable: false),
                    CreatesVoucher = table.Column<bool>(type: "bit", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_InvoiceTypes", x => x.TypeID);
                });

            // Seed InvoiceTypes
            migrationBuilder.Sql(@"
                SET IDENTITY_INSERT [InvoiceTypes] ON;
                INSERT INTO [InvoiceTypes] ([TypeID], [Code], [Name], [Category], [Direction], [AffectsStock], [CreatesVoucher], [IsActive])
                VALUES 
                    (1, 'SALE', 'Sales Invoice', 'SALE', -1, 1, 1, 1),
                    (2, 'PURCHASE', 'Purchase Invoice (GRN)', 'PURCHASE', 1, 1, 1, 1),
                    (3, 'SALE_RTN', 'Sales Return', 'SALE', 1, 1, 1, 1),
                    (4, 'PURCH_RTN', 'Purchase Return', 'PURCHASE', -1, 1, 1, 1),
                    (5, 'ADJ', 'Stock Adjustment', 'INVENTORY', 0, 1, 1, 1),
                    (6, 'XFER_OUT', 'Transfer Out', 'INVENTORY', -1, 1, 0, 1),
                    (7, 'XFER_IN', 'Transfer In', 'INVENTORY', 1, 1, 0, 1),
                    (8, 'TAKE', 'Stock Take', 'INVENTORY', 0, 1, 1, 1),
                    (9, 'PO', 'Purchase Order', 'PURCHASE', 0, 0, 0, 1);
                SET IDENTITY_INSERT [InvoiceTypes] OFF;
            ");

            // Seed AccountVoucherTypes
            migrationBuilder.Sql(@"
                SET IDENTITY_INSERT [AccountVoucherTypes] ON;
                INSERT INTO [AccountVoucherTypes] ([VoucherTypeID], [Code], [Name], [AutoGenerated], [IsActive])
                VALUES 
                    (1, 'JV', 'Journal Voucher', 1, 1),
                    (2, 'BP', 'Bank Payment', 0, 1),
                    (3, 'BR', 'Bank Receipt', 0, 1),
                    (4, 'CP', 'Cash Payment', 0, 1),
                    (5, 'CR', 'Cash Receipt', 0, 1);
                SET IDENTITY_INSERT [AccountVoucherTypes] OFF;
            ");

            migrationBuilder.CreateTable(
                name: "AccountVouchers",
                columns: table => new
                {
                    VoucherID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    VoucherType_ID = table.Column<int>(type: "int", nullable: false),
                    VoucherCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    VoucherDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    SourceTable = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    SourceID = table.Column<int>(type: "int", nullable: true),
                    Store_ID = table.Column<int>(type: "int", nullable: true),
                    FiscalPeriod_ID = table.Column<int>(type: "int", nullable: true),
                    TotalDebit = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    TotalCredit = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    Status = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    IsReversed = table.Column<bool>(type: "bit", nullable: false),
                    ReversedBy_ID = table.Column<int>(type: "int", nullable: true),
                    Reverses_ID = table.Column<int>(type: "int", nullable: true),
                    Narration = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    CreatedBy = table.Column<int>(type: "int", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AccountVouchers", x => x.VoucherID);
                    table.ForeignKey(
                        name: "FK_AccountVouchers_AccountVoucherTypes_VoucherType_ID",
                        column: x => x.VoucherType_ID,
                        principalTable: "AccountVoucherTypes",
                        principalColumn: "VoucherTypeID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_AccountVouchers_AccountVouchers_ReversedBy_ID",
                        column: x => x.ReversedBy_ID,
                        principalTable: "AccountVouchers",
                        principalColumn: "VoucherID");
                    table.ForeignKey(
                        name: "FK_AccountVouchers_AccountVouchers_Reverses_ID",
                        column: x => x.Reverses_ID,
                        principalTable: "AccountVouchers",
                        principalColumn: "VoucherID");
                    table.ForeignKey(
                        name: "FK_AccountVouchers_FiscalPeriods_FiscalPeriod_ID",
                        column: x => x.FiscalPeriod_ID,
                        principalTable: "FiscalPeriods",
                        principalColumn: "FiscalPeriodID",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "FK_AccountVouchers_Stores_Store_ID",
                        column: x => x.Store_ID,
                        principalTable: "Stores",
                        principalColumn: "StoreID",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateTable(
                name: "AccountVoucherDetails",
                columns: table => new
                {
                    VoucherDetailID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Voucher_ID = table.Column<int>(type: "int", nullable: false),
                    Account_ID = table.Column<int>(type: "int", nullable: false),
                    Dr = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    Cr = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    Product_ID = table.Column<int>(type: "int", nullable: true),
                    Particulars = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    Store_ID = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AccountVoucherDetails", x => x.VoucherDetailID);
                    table.ForeignKey(
                        name: "FK_AccountVoucherDetails_AccountVouchers_Voucher_ID",
                        column: x => x.Voucher_ID,
                        principalTable: "AccountVouchers",
                        principalColumn: "VoucherID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_AccountVoucherDetails_ChartOfAccounts_Account_ID",
                        column: x => x.Account_ID,
                        principalTable: "ChartOfAccounts",
                        principalColumn: "AccountID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_AccountVoucherDetails_Products_Product_ID",
                        column: x => x.Product_ID,
                        principalTable: "Products",
                        principalColumn: "ProductID",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "FK_AccountVoucherDetails_Stores_Store_ID",
                        column: x => x.Store_ID,
                        principalTable: "Stores",
                        principalColumn: "StoreID",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateTable(
                name: "StockMains",
                columns: table => new
                {
                    StockMainID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    InvoiceType_ID = table.Column<int>(type: "int", nullable: false),
                    InvoiceNo = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    InvoiceDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Store_ID = table.Column<int>(type: "int", nullable: false),
                    Party_ID = table.Column<int>(type: "int", nullable: true),
                    SubTotal = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    DiscountPercent = table.Column<decimal>(type: "decimal(5,2)", nullable: true),
                    DiscountAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    TotalAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    PaidAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    BalanceAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    Status = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: false),
                    PaymentStatus = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    PaymentVoucher_ID = table.Column<int>(type: "int", nullable: true),
                    Account_ID = table.Column<int>(type: "int", nullable: true),
                    ReferenceStockMain_ID = table.Column<int>(type: "int", nullable: true),
                    Remarks = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    SupplierInvoiceNo = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    VoidReason = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    VoidedBy = table.Column<int>(type: "int", nullable: true),
                    VoidedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ReturnReason = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    ReturnNotes = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    RefundMethod = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    RefundStatus = table.Column<string>(type: "nvarchar(20)", maxLength: 20, nullable: true),
                    RefundAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    RefundVoucher_ID = table.Column<int>(type: "int", nullable: true),
                    DestinationStore_ID = table.Column<int>(type: "int", nullable: true),
                    ReceivedBy = table.Column<int>(type: "int", nullable: true),
                    ReceivedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CompletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CompletedBy = table.Column<int>(type: "int", nullable: true),
                    ExpectedDeliveryDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    CreatedBy = table.Column<int>(type: "int", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    UpdatedBy = table.Column<int>(type: "int", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StockMains", x => x.StockMainID);
                    table.ForeignKey(
                        name: "FK_StockMains_AccountVouchers_PaymentVoucher_ID",
                        column: x => x.PaymentVoucher_ID,
                        principalTable: "AccountVouchers",
                        principalColumn: "VoucherID");
                    table.ForeignKey(
                        name: "FK_StockMains_AccountVouchers_RefundVoucher_ID",
                        column: x => x.RefundVoucher_ID,
                        principalTable: "AccountVouchers",
                        principalColumn: "VoucherID");
                    table.ForeignKey(
                        name: "FK_StockMains_ChartOfAccounts_Account_ID",
                        column: x => x.Account_ID,
                        principalTable: "ChartOfAccounts",
                        principalColumn: "AccountID",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "FK_StockMains_InvoiceTypes_InvoiceType_ID",
                        column: x => x.InvoiceType_ID,
                        principalTable: "InvoiceTypes",
                        principalColumn: "TypeID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_StockMains_Parties_Party_ID",
                        column: x => x.Party_ID,
                        principalTable: "Parties",
                        principalColumn: "PartyID",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "FK_StockMains_StockMains_ReferenceStockMain_ID",
                        column: x => x.ReferenceStockMain_ID,
                        principalTable: "StockMains",
                        principalColumn: "StockMainID");
                    table.ForeignKey(
                        name: "FK_StockMains_Stores_DestinationStore_ID",
                        column: x => x.DestinationStore_ID,
                        principalTable: "Stores",
                        principalColumn: "StoreID");
                    table.ForeignKey(
                        name: "FK_StockMains_Stores_Store_ID",
                        column: x => x.Store_ID,
                        principalTable: "Stores",
                        principalColumn: "StoreID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "StockDetails",
                columns: table => new
                {
                    StockDetailID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StockMain_ID = table.Column<int>(type: "int", nullable: false),
                    Product_ID = table.Column<int>(type: "int", nullable: false),
                    ProductBatch_ID = table.Column<int>(type: "int", nullable: true),
                    Quantity = table.Column<decimal>(type: "decimal(18,4)", nullable: false),
                    UnitPrice = table.Column<decimal>(type: "decimal(18,4)", nullable: false),
                    PurchasePrice = table.Column<decimal>(type: "decimal(18,4)", nullable: false),
                    DiscountPercent = table.Column<decimal>(type: "decimal(5,2)", nullable: true),
                    DiscountAmount = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    LineTotal = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    LineCost = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    SystemQuantity = table.Column<decimal>(type: "decimal(18,4)", nullable: true),
                    PhysicalQuantity = table.Column<decimal>(type: "decimal(18,4)", nullable: true),
                    VarianceCost = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ReturnReason = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    MovementType = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: true),
                    TotalCost = table.Column<decimal>(type: "decimal(18,4)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StockDetails", x => x.StockDetailID);
                    table.ForeignKey(
                        name: "FK_StockDetails_ProductBatches_ProductBatch_ID",
                        column: x => x.ProductBatch_ID,
                        principalTable: "ProductBatches",
                        principalColumn: "ProductBatchID",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "FK_StockDetails_Products_Product_ID",
                        column: x => x.Product_ID,
                        principalTable: "Products",
                        principalColumn: "ProductID",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_StockDetails_StockMains_StockMain_ID",
                        column: x => x.StockMain_ID,
                        principalTable: "StockMains",
                        principalColumn: "StockMainID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_AccountVoucherDetails_Account_ID",
                table: "AccountVoucherDetails",
                column: "Account_ID");

            migrationBuilder.CreateIndex(
                name: "IX_AccountVoucherDetails_Product_ID",
                table: "AccountVoucherDetails",
                column: "Product_ID");

            migrationBuilder.CreateIndex(
                name: "IX_AccountVoucherDetails_Store_ID",
                table: "AccountVoucherDetails",
                column: "Store_ID");

            migrationBuilder.CreateIndex(
                name: "IX_AccountVoucherDetails_Voucher_ID",
                table: "AccountVoucherDetails",
                column: "Voucher_ID");

            migrationBuilder.CreateIndex(
                name: "IX_AccountVouchers_FiscalPeriod_ID",
                table: "AccountVouchers",
                column: "FiscalPeriod_ID");

            migrationBuilder.CreateIndex(
                name: "IX_AccountVouchers_ReversedBy_ID",
                table: "AccountVouchers",
                column: "ReversedBy_ID",
                unique: true,
                filter: "[ReversedBy_ID] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_AccountVouchers_Reverses_ID",
                table: "AccountVouchers",
                column: "Reverses_ID",
                unique: true,
                filter: "[Reverses_ID] IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_AccountVouchers_Store_ID",
                table: "AccountVouchers",
                column: "Store_ID");

            migrationBuilder.CreateIndex(
                name: "IX_AccountVouchers_VoucherCode",
                table: "AccountVouchers",
                column: "VoucherCode",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_AccountVouchers_VoucherType_ID",
                table: "AccountVouchers",
                column: "VoucherType_ID");

            migrationBuilder.CreateIndex(
                name: "IX_AccountVoucherTypes_Code",
                table: "AccountVoucherTypes",
                column: "Code",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_InvoiceTypes_Code",
                table: "InvoiceTypes",
                column: "Code",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_StockDetails_Product_ID",
                table: "StockDetails",
                column: "Product_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockDetails_ProductBatch_ID",
                table: "StockDetails",
                column: "ProductBatch_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockDetails_StockMain_ID",
                table: "StockDetails",
                column: "StockMain_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockMains_Account_ID",
                table: "StockMains",
                column: "Account_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockMains_DestinationStore_ID",
                table: "StockMains",
                column: "DestinationStore_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockMains_InvoiceNo",
                table: "StockMains",
                column: "InvoiceNo",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_StockMains_InvoiceType_ID",
                table: "StockMains",
                column: "InvoiceType_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockMains_Party_ID",
                table: "StockMains",
                column: "Party_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockMains_PaymentVoucher_ID",
                table: "StockMains",
                column: "PaymentVoucher_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockMains_ReferenceStockMain_ID",
                table: "StockMains",
                column: "ReferenceStockMain_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockMains_RefundVoucher_ID",
                table: "StockMains",
                column: "RefundVoucher_ID");

            migrationBuilder.CreateIndex(
                name: "IX_StockMains_Store_ID",
                table: "StockMains",
                column: "Store_ID");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AccountVoucherDetails");

            migrationBuilder.DropTable(
                name: "StockDetails");

            migrationBuilder.DropTable(
                name: "StockMains");

            migrationBuilder.DropTable(
                name: "AccountVouchers");

            migrationBuilder.DropTable(
                name: "InvoiceTypes");

            migrationBuilder.DropTable(
                name: "AccountVoucherTypes");
        }
    }
}
