using Microsoft.EntityFrameworkCore;
using PharmaCare.Application.DTOs;
using PharmaCare.Application.DTOs.Transactions;
using PharmaCare.Application.Interfaces;
using PharmaCare.Application.Interfaces.Transactions;
using PharmaCare.Application.Utilities;
using PharmaCare.Domain.Entities.Transactions;

namespace PharmaCare.Application.Implementations.Transactions;

public class JournalVoucherService : IJournalVoucherService
{
    private readonly IRepository<Voucher> _voucherRepository;
    private readonly IRepository<VoucherType> _voucherTypeRepository;
    private readonly IUnitOfWork _unitOfWork;

    public JournalVoucherService(
        IRepository<Voucher> voucherRepository,
        IRepository<VoucherType> voucherTypeRepository,
        IUnitOfWork unitOfWork)
    {
        _voucherRepository = voucherRepository;
        _voucherTypeRepository = voucherTypeRepository;
        _unitOfWork = unitOfWork;
    }

    public async Task<IEnumerable<Voucher>> GetAllJournalVouchersAsync()
    {
        // Get all vouchers of type 'JV'
        // Include type to verify? Or just filter by non-auto-generated?
        // Assuming "JV" is the code for manual journals.
        
        return await _voucherRepository.Query()
            .Include(v => v.VoucherType)
            .Where(v => v.VoucherType.Code == "JV")
            .OrderByDescending(v=>v.VoucherID)
            .ToListAsync();
    }

    public async Task<PagedResult<Voucher>> GetPagedJournalVouchersAsync(string? search, string? status, int page, int pageSize)
    {
        var query = _voucherRepository.Query()
            .AsNoTracking()
            .Include(v => v.VoucherType)
            .Where(v => v.VoucherType.Code == "JV");

        if (!string.IsNullOrWhiteSpace(search))
        {
            var term = search.Trim();
            query = query.Where(v => v.VoucherNo.Contains(term) || (v.Narration != null && v.Narration.Contains(term)));
        }

        if (!string.IsNullOrWhiteSpace(status) && status != "All")
            query = query.Where(v => v.Status == status);

        int totalCount = await query.CountAsync();

        var items = await query
            .OrderByDescending(v => v.VoucherID)
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .ToListAsync();

        return new PagedResult<Voucher>
        {
            Items = items,
            TotalCount = totalCount,
            CurrentPage = page,
            PageSize = pageSize
        };
    }

    public async Task<Voucher?> GetByIdAsync(int id)
    {
        return await _voucherRepository.Query()
            .Include(v => v.VoucherDetails)
                .ThenInclude(vd => vd.Account)
            .Include(v => v.VoucherType)
            .FirstOrDefaultAsync(v => v.VoucherID == id);
    }

    public async Task<Voucher> CreateJournalVoucherAsync(JournalVoucherDto model, int userId)
    {
        // 1. Get JV Type
        var jvType = await _voucherTypeRepository.GetByIdAsync(model.VoucherType_ID);
        if (jvType == null)
            throw new Exception("Voucher Type not found.");
        
        if (jvType.IsAutoGenerated)
             throw new Exception("Cannot manually create an auto-generated voucher type.");

        // SECURITY: Recalculate totals from details instead of trusting model scalars
        decimal calculatedTotalDebit = model.VoucherDetails.Sum(d => d.DebitAmount);
        decimal calculatedTotalCredit = model.VoucherDetails.Sum(d => d.CreditAmount);

        if (calculatedTotalDebit != calculatedTotalCredit)
             throw new InvalidOperationException("Voucher must be balanced. Total Debit must equal Total Credit.");

        if (calculatedTotalDebit <= 0)
             throw new InvalidOperationException("Voucher amount must be greater than zero.");

        // SANITY CHECK: Prevent nonsensical amounts
        if (calculatedTotalDebit > AccountingConstants.MaxTransactionAmount)
             throw new InvalidOperationException("Voucher amount exceeds sanity limit (100 Million).");

        // 2. Map ViewModel to Entity
        var voucher = new Voucher
        {
            VoucherType_ID = jvType.VoucherTypeID,
            VoucherNo = await GenerateVoucherNoAsync(),
            VoucherDate = model.VoucherDate,
            Narration = model.Narration,
            Status = "Posted",
            TotalDebit = calculatedTotalDebit,
            TotalCredit = calculatedTotalCredit,
            IsReversed = false,
            CreatedAt = AppTime.Now,
            CreatedBy = userId
        };

        // 3. Add Details
        foreach (var det in model.VoucherDetails)
        {
            voucher.VoucherDetails.Add(new VoucherDetail
            {
                Account_ID = det.Account_ID,
                DebitAmount = det.DebitAmount,
                CreditAmount = det.CreditAmount,
                Description = det.Description
            });
        }

        // 4. Save
        await _voucherRepository.AddAsync(voucher);
        await _unitOfWork.SaveChangesAsync();

        return voucher;
    }

    public async Task<bool> VoidVoucherAsync(int voucherId, string reason, int userId)
    {
        var original = await GetByIdAsync(voucherId);
        if (original == null) return false;
        if (original.IsReversed || original.ReversesVoucher_ID != null)
            throw new Exception("Reversal not allowed. This voucher is already reversed or is itself a reversal entry.");

        // 1. Mark Original as Reversed
        original.IsReversed = true;
        original.Status = "Reversed";
        original.VoidReason = reason;
        
        // 2. Create Reversal Voucher
        var reversal = new Voucher
        {
            VoucherType_ID = original.VoucherType_ID,
            VoucherNo = await GenerateVoucherNoAsync(),
            VoucherDate = AppTime.Now, // Reversal date is NOW
            Narration = $"Reversal of {original.VoucherNo} - {reason}",
            Status = "Posted", // The reversal itself is a valid posted transaction
            TotalDebit = original.TotalCredit, // Swapped for header? Usually header totals are just sum of lines. 
            // Actually, TotalDebit/Credit in header usually represents the volume. 
            // But let's stick to simple sum.
            TotalCredit = original.TotalDebit, 
            IsReversed = false,
            ReversesVoucher_ID = original.VoucherID,
            CreatedAt = AppTime.Now,
            CreatedBy = userId
        };
        
        // 3. Create Reversal Details (Swap Debit/Credit)
        foreach (var det in original.VoucherDetails)
        {
            reversal.VoucherDetails.Add(new VoucherDetail
            {
                Account_ID = det.Account_ID,
                DebitAmount = det.CreditAmount, // Swap
                CreditAmount = det.DebitAmount, // Swap
                Description = $"Reversal: {det.Description}"
            });
        }

        await _voucherRepository.AddAsync(reversal);
        // Note: effectively we need to save Reversal first to get ID? 
        // EF Core handles ID fixup. But we need to link Original.ReversedBy -> Reversal.
        
        // We add Reversal, then update Original.ReversedBy
        
        await _unitOfWork.SaveChangesAsync(); // Save Reversal to get ID
        
        original.ReversedByVoucher_ID = reversal.VoucherID; // Link
        _voucherRepository.Update(original);
        
        await _unitOfWork.SaveChangesAsync(); // Update Original

        return true;
    }

    public async Task<string> GenerateVoucherNoAsync()
    {
        // Shared generator: JV-yyyyMMdd-XXXX (serialized when called inside a transaction)
        return await _voucherRepository.GenerateVoucherNoAsync("JV", _unitOfWork);
    }
}
