using System.ComponentModel.DataAnnotations;

namespace PharmaCare.Domain.Entities.Transactions;

/// <summary>
/// Voucher Type lookup - defines accounting voucher categories.
/// </summary>
public class VoucherType
{
    [Key]
    public int VoucherTypeID { get; set; }

    /// <summary>
    /// Short code: JV, PV, RV, CV, SV, PRV, EXP, ADJ
    /// </summary>
    [Required]
    [StringLength(10)]
    public string Code { get; set; } = string.Empty;

    [Required]
    [StringLength(50)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Whether vouchers of this type are auto-generated by system
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    public bool IsActive { get; set; } = true;
}
