using System.ComponentModel.DataAnnotations;

namespace PharmaCare.Domain.Models.Inventory;

/// <summary>
/// Lookup table for accounting voucher types
/// </summary>
public class AccountVoucherType
{
    [Key]
    public int VoucherTypeID { get; set; }

    [Required]
    [MaxLength(10)]
    public string Code { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Whether vouchers of this type are auto-generated by system
    /// </summary>
    public bool AutoGenerated { get; set; }

    public bool IsActive { get; set; } = true;
}
