using PharmaCare.Application.Interfaces.Transactions;
using PharmaCare.Domain.Entities.Configuration;
using PharmaCare.Domain.Entities.Transactions;
using Microsoft.EntityFrameworkCore;

namespace PharmaCare.IntegrationTests;

/// <summary>
/// Stock on hand is DERIVED from movement history, which makes every availability check a
/// read-then-write. Two tills serving the last packet at the same moment is the ordinary case in a
/// pharmacy, not an exotic one — if the application lock does not hold, stock goes negative and the
/// shop has sold something it does not have.
///
/// <para>
/// These tests deliberately use separate DI scopes, because two concurrent requests each get their
/// own DbContext. Sharing one would test EF's change tracker, not the database lock.
/// </para>
/// </summary>
[Collection(Collections.Database)]
public class ConcurrencyTests
{
    private readonly DatabaseFixture _fixture;

    public ConcurrencyTests(DatabaseFixture fixture) => _fixture = fixture;

    private static StockMain Sale(Party customer, Product product, decimal qty, decimal price)
        => new()
        {
            Party_ID = customer.PartyID,
            TransactionDate = AppTime.Now,
            PaidAmount = qty * price,
            StockDetails = new List<StockDetail>
            {
                new() { Product_ID = product.ProductID, Quantity = qty, UnitPrice = price }
            }
        };

    [Fact]
    public async Task Two_tills_selling_the_last_unit_cannot_both_succeed()
    {
        using var tenant = await _fixture.NewTenantAsync();
        var world = await tenant.SeedWorldAsync();
        await tenant.ReceiveStockAsync(world.Supplier, world.Product, 1, unitCost: 10m);

        using var tillA = await _fixture.ScopeForAsync(tenant.PharmacyId);
        using var tillB = await _fixture.ScopeForAsync(tenant.PharmacyId);

        var results = await Task.WhenAll(
            Record.ExceptionAsync(() => tillA.Get<ISaleService>().CreateAsync(
                Sale(world.Customer, world.Product, 1, 20m), TenantData.TestUserId, world.Cash.AccountID)),
            Record.ExceptionAsync(() => tillB.Get<ISaleService>().CreateAsync(
                Sale(world.Customer, world.Product, 1, 20m), TenantData.TestUserId, world.Cash.AccountID)));

        var succeeded = results.Count(e => e is null);

        Assert.Equal(1, succeeded);
        Assert.Equal(0m, await tenant.StockOnHandAsync(world.Product.ProductID));
    }

    /// <summary>
    /// The stronger claim: whatever interleaving occurs, derived stock must never end up negative.
    /// </summary>
    [Fact]
    public async Task Concurrent_sales_never_drive_stock_negative()
    {
        using var tenant = await _fixture.NewTenantAsync();
        var world = await tenant.SeedWorldAsync();
        await tenant.ReceiveStockAsync(world.Supplier, world.Product, 10, unitCost: 10m);

        var scopes = new List<TenantScope>();
        try
        {
            for (var i = 0; i < 6; i++) scopes.Add(await _fixture.ScopeForAsync(tenant.PharmacyId));

            // Six tills each try for 3 units against 10 on hand: at most three can win.
            var attempts = scopes.Select(scope => Record.ExceptionAsync(() =>
                scope.Get<ISaleService>().CreateAsync(
                    Sale(world.Customer, world.Product, 3, 20m), TenantData.TestUserId, world.Cash.AccountID)));

            var results = await Task.WhenAll(attempts);
            var succeeded = results.Count(e => e is null);

            var onHand = await tenant.StockOnHandAsync(world.Product.ProductID);

            Assert.True(onHand >= 0, $"stock went negative: {onHand}");
            Assert.True(succeeded <= 3, $"{succeeded} sales of 3 units succeeded against 10 units of stock");
            Assert.Equal(10m - (succeeded * 3), onHand);
        }
        finally
        {
            foreach (var scope in scopes) scope.Dispose();
        }
    }

    /// <summary>
    /// Document numbers are generated by reading the highest existing number and adding one.
    /// Concurrent transactions must not be handed the same number — a duplicate invoice number is
    /// a compliance problem, not just a cosmetic one.
    /// </summary>
    [Fact]
    public async Task Concurrent_sales_are_given_distinct_transaction_numbers()
    {
        using var tenant = await _fixture.NewTenantAsync();
        var world = await tenant.SeedWorldAsync();
        await tenant.ReceiveStockAsync(world.Supplier, world.Product, 1000, unitCost: 10m);

        var scopes = new List<TenantScope>();
        try
        {
            for (var i = 0; i < 8; i++) scopes.Add(await _fixture.ScopeForAsync(tenant.PharmacyId));

            var results = await Task.WhenAll(scopes.Select(scope =>
                scope.Get<ISaleService>().CreateAsync(
                    Sale(world.Customer, world.Product, 1, 20m), TenantData.TestUserId, world.Cash.AccountID)));

            var numbers = results.Select(r => r.TransactionNo).ToList();
            Assert.Equal(numbers.Count, numbers.Distinct().Count());
        }
        finally
        {
            foreach (var scope in scopes) scope.Dispose();
        }
    }

    /// <summary>
    /// Same question for the ledger: two vouchers sharing a number would make the general ledger
    /// ambiguous.
    /// </summary>
    [Fact]
    public async Task Concurrent_postings_are_given_distinct_voucher_numbers()
    {
        using var tenant = await _fixture.NewTenantAsync();
        var world = await tenant.SeedWorldAsync();
        await tenant.ReceiveStockAsync(world.Supplier, world.Product, 1000, unitCost: 10m);

        var scopes = new List<TenantScope>();
        try
        {
            for (var i = 0; i < 8; i++) scopes.Add(await _fixture.ScopeForAsync(tenant.PharmacyId));

            await Task.WhenAll(scopes.Select(scope =>
                scope.Get<ISaleService>().CreateAsync(
                    Sale(world.Customer, world.Product, 1, 20m), TenantData.TestUserId, world.Cash.AccountID)));

            var voucherNos = await tenant.Db.Vouchers.Select(v => v.VoucherNo).ToListAsync();
            Assert.Equal(voucherNos.Count, voucherNos.Distinct().Count());
        }
        finally
        {
            foreach (var scope in scopes) scope.Dispose();
        }
    }
}
